import type { Metadata } from 'next';
import './globals.css';

import App from './app';

export const metadata: Metadata = {
  title: 'MOVIEPEDIA',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          rel="stylesheet"
        />
        <link
          href="https://uicdn.toast.com/calendar/latest/toastui-calendar.min.css"
          rel="stylesheet"
        />
        <script
          src="https://uicdn.toast.com/calendar/latest/toastui-calendar.min.js"
          defer
        ></script>
      </head>
      <body>
        <div className="wrap">
          <App>{children}</App>
        </div>
      </body>
    </html>
  );
}
